[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  targetPort = 3000

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
